POST http://localhost:5000/auth/register HTTP/1.1
Content-Type: application/json

{
  "username": "qqh",
  "password": "password123"
}




# POST https://kiwicode.tech/myasorobka/api/auth/register HTTP/1.1
# Content-Type: application/json

# {
#   "username": "qqwjtw",
#   "password": "password123"
# }