PUT http://localhost:5000/product/64b111a1ed0e40e31fb2d14f HTTP/1.1
Content-Type: application/json

{
  "category": "new_category",
  "discount_price": 123456,
  "name": "new",
  "price": 99,
  "unit": "pieces",
  "available": true,
  "description": "new_description",
  "favourite": false,
  "img": "new_url"
}

# PUT https://kiwicode.tech/myasorobka/api/product/64b111a1ed0e40e31fb2d14f HTTP/1.1
# Content-Type: application/json

# {
#   "category": "new_category",
#   "discount_price": 123456,
#   "name": "new",
#   "price": 999,
#   "unit": "pieces",
#   "available": true,
#   "description": "new_description",
#   "favourite": false,
#   "img": "new_url"
# }
